kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: androidsdk/android-28
  push:
    commands:
      - "./gradlew clean build"
      - echo "${DRONE_BRANCH}"
      - bash ./gradlew test --stacktrace
  when:
    event:
    - push
